# Generated by Django 6.0.6 on 2026-06-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_seed_board_and_migrate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
